Repository digitalearthpacific/dep-seagrass, pull requests merged in 2025-07, with the labels that each got.

#76 reduce
  classification/3-combined-workflow-sea-rf-12052025.ipynb
  classification/3-glcm-texture-03062025_waqa_updated.ipynb
  classification/models/site_rf_14052025-test.model
  classification/site_rf_14052025_high_correlation_matrix.csv
  classification/site_rf_14052025importance_df.csv
  classification/sorted.csv
Labels: documentation

#81 Test branch
  classification/3-glcm-texture-incorporation-02072025.ipynb
  classification/3-glcm-texture-incorporation-04072025.ipynb
  classification/mask-testing.ipynb
  classification/utils.py
Labels: documentation, good first issue

#83 updated texture analysis
  classification/3-glcm-texture-incorporation-bootless-05072025.ipynb
  classification/3-glcm-texture-incorporation-utanglang-04072025.ipynb
  classification/3-glcm-texture-incorporation-utanglang-05072025.ipynb
  classification/models/nm-bootless-04-07-2025-test.model
  classification/models/nm-utanglang-04-07-2025-test.model
  classification/nm-utanglang-04-07-2025_high_correlation_matrix.csv
  classification/nm-utanglang-04-07-2025importance_df.csv
  classification/site_rf_10062025_high_correlation_matrix.csv
  classification/training-data/35_params_tdata_04072025.csv
  classification/training-data/nm-bootless-04-07-202535_params_tdata_04072025.csv
  classification/utils.py
Labels: documentation, enhancement

#84 Test branch
  classification/3-glcm-texture-incorporation-bootless-05072025.ipynb
  classification/drafts/3-combined-workflow-sea-rf-12052025.ipynb
  classification/drafts/3-combined-workflow-texture-10062025.ipynb
  classification/drafts/3-glcm-texture-03062025.ipynb
  classification/drafts/3-glcm-texture-incorporation-02072025.ipynb
  classification/drafts/3-glcm-texture-incorporation-04072025.ipynb
  classification/drafts/3-glcm-texture-incorporation-utanglang-04072025.ipynb
  classification/drafts/3-glcm-texture-incorporation-utanglang-05072025.ipynb
  classification/drafts/3-prediction-workflow-rf.ipynb
  classification/drafts/4-test-prediction-workflow-rf-22052025.ipynb
  classification/models/nm-bootless-04-07-2025-test.model
  classification/models/nm-utanglang-04-07-2025-test.model
  classification/nm-bootless-04-07-2025_importance_df.csv
  classification/training-data/35_params_tdata_04072025.csv
  classification/training-data/nm-bootless-04-07-202535_params_tdata_04072025.csv
  classification/utils.py
Labels: documentation

#90 added mask and util_test and mal.geojson
  classification/mask testing.ipynb
  classification/training-data/mal.geojson
  classification/utils_test.py
Labels: documentation, help wanted

#94 update for Elenoa
  classification/3-glcm-texture-incorporation-bootless-05072025-AL.ipynb
Labels: documentation, help wanted

#96 trying to integrate dem mask
  classification/3-glcm-texture-incorporation-bootless-05072025-AL.ipynb
Labels: documentation

#99 upload for gemini
  classification/3-glcm-texture-incorporation-bootless-05072025-AL.ipynb
Labels: documentation, enhancement

#101 debugged 1
  classification/3-glcm-texture-incorporation-bootless-05072025-AL-Copy1.ipynb
  classification/3-glcm-texture-incorporation-bootless-05072025-AL.ipynb
  classification/ElenoaElevation_Masking.ipynb
  classification/JoshBrown_Mask_testing.ipynb
Labels: documentation

#102 debugged2
  classification/3-glcm-texture-incorporation-bootless-05072025-AL-Copy1.ipynb
  classification/training-data/agl-bootless-09072025-training.csv
Labels: documentation, enhancement

#105 abstraction process started
  classification/3-glcm-texture-incorporation-bootless-05072025-AL-Copy1.ipynb
  classification/utils.py
Labels: documentation

#107 checkpoint
  classification/3-glcm-texture-incorporation-bootless-05072025-AL-Copy1.ipynb
Labels: documentation

#111 backup before cleaning
  classification/1-generate-postcard-csv.ipynb
  classification/3-glcm-texture-incorporation-bootless-05072025-AL-Copy2.ipynb
  classification/3-glcm-texture-incorporation-bootless-05072025-AL.ipynb
  classification/ElenoaElevation_Masking.ipynb
  classification/JoshBrown_Mask_testing.ipynb
  classification/nm-bootless-04-07-2025_importance_df.csv
  classification/sdb/sdb_cog_exporter.ipynb
  classification/training-data/agl-bootless-11072025-training.csv
  classification/utils.py
Labels: documentation

#115 tidying up seagrass repo 1
  classification/1-generate-postcard-csv.ipynb
  classification/training-data/agl-bootless-11072025-training.csv
  classification/utils.py
Labels: documentation

#119 updated - but dask is struggling with code cell 19
  classification/1-generate-postcard-csv.ipynb
  classification/training-data/agl-bootless-11072025-training.csv
  classification/training-data/agl-bootless-12072025-training.csv
Labels: bug, documentation

#121 added dask client
  classification/1-generate-postcard-csv.ipynb
Labels: documentation

#122 first full workflow run through test
  classification/1-generate-postcard-csv.ipynb
  classification/2-joining-csvs.ipynb
  classification/3-model-training-prediction.ipynb
  classification/training-data/bootless-bay_postcard.geojson
  classification/training-data/nm-14072025-joined_tdata.csv
  classification/training-data/nm-bootless-bay-13072025_postcard.geojson
  classification/training-data/nm-bootless_bay-13072025-training.csv
  classification/training-data/nm-honiara-1407072025_postcard.geojson
  classification/training-data/nm-serua-13072025_postcard.geojson
  classification/training-data/nm-serua-14072025-training.csv
  classification/training-data/nm-serua-14072025_postcard.geojson
  classification/training-data/nm-tulagi-13072025_postcard.geojson
  classification/training-data/nm-tulagi-1407072025_postcard.geojson
Labels: documentation, enhancement

#123 reconciling notebooks 1
  classification/1-generate-postcard-csv.ipynb
  classification/3-model-training-prediction.ipynb
  classification/training-data/bootless-bay_postcard.geojson
  classification/training-data/nm-serua-14072025-training.csv
  classification/utils.py
Labels: documentation, help wanted

#126 completed first full workflow
  classification/3-model-training.ipynb
  classification/4-run-predictions.ipynb
  classification/models/nm-15072025-test.model
Labels: documentation, enhancement

#127 trying to work on masking functions based on sdb examples from Alex
  classification/0-preprocessing-tdata-geopandas.ipynb
  classification/1-generate-postcard-csv.ipynb
  classification/4-run-predictions.ipynb
  classification/training-data/nm-bootless-15072025-training.csv
  classification/training-data/nm-honiara-14072025_postcard.geojson
  classification/training-data/utanglang_postcard.geojson
  classification/utils.py
Labels: bug, documentation, help wanted

#129 update and clean notebooks including 4
  classification/1-generate-postcard-csv-Copy1.ipynb
  classification/1-generate-postcard-csv.ipynb
  classification/4-run-predictions.ipynb
  classification/training-data/nm-bootless-15072025-training.csv
  classification/training-data/nm-bootless-16072025-training.csv
  classification/utils.py
Labels: documentation

#130 4 - model prediction
  classification/1-generate-postcard-csv-Copy1.ipynb
  classification/1-generate-postcard-csv.ipynb
  classification/4-run-predictions.ipynb
  classification/4b-model-training.ipynb
Labels: documentation, enhancement

#132 modified model and re-ran all steps of workflow
  classification/0-preprocessing-tdata-geopandas.ipynb
  classification/1-generate-postcard-csv.ipynb
  classification/3-model-training.ipynb
  classification/5-model-training.ipynb
  classification/models/nm-15072025-test.model
  classification/models/nm-16072025-test.model
  classification/seagress_pred_1
  classification/training-data/nm-16072025-joined_tdata.csv
  classification/training-data/nm-serua-16072025-training.csv
Labels: documentation

#136 updating based on meet with Alex
  classification/5-model-training.ipynb
  classification/utils.py
Labels: documentation, good first issue, help wanted

#138 still unsure about the mask issue
  classification/4-run-predictions.ipynb
  classification/5-model-training.ipynb
Labels: bug, documentation, help wanted

#139 issue with prediction mask export
  classification/3-model-training.ipynb
  classification/5-model-training.ipynb
Labels: bug, documentation, help wanted

#141 updated notebook 0
  classification/0-preprocessing-tdata-geopandas.ipynb
Labels: documentation, enhancement

#142 updated deep sea to -0.02
  classification/1-generate-postcard-csv.ipynb
  classification/4-prediction.ipynb
  classification/training-data/nm-bootless-18072025-training.csv
  classification/utils.py
Labels: documentation, enhancement

#144 updates to the repo for scaling 1
  classification/src/print_tasks_geomad_example.py
  classification/src/run_task_geomad_example.py
  classification/src/utils_geomad_example.py
Labels: documentation

#145 update with scaling
  src/print_tasks_geomad_example.py
  src/run_task_geomad_example.py
  src/utils_geomad_example.py
Labels: documentation

#146 updated files for scaling
  classification/3-model-training.ipynb
  classification/4-prediction.ipynb
  classification/src/print_tasks_geomad_example.py
  classification/src/run_task_geomad_example.py
  classification/src/utils_geomad_example.py
  classification/utils.py
Labels: documentation

#148 working on probability
  classification/utils.py
Labels: documentation

#150 completed first round probability
  classification/4-prediction.ipynb
  classification/utils.py
Labels: documentation, enhancement

#151 revised to generate 80% probability threshold
  classification/4-prediction.ipynb
  classification/utils.py
Labels: documentation, enhancement

#154 revised utils
  classification/4-prediction.ipynb
  classification/utils.py
Labels: documentation

#157 update remaining files
  classification/4-prediction.ipynb
  classification/training-data/nm-17072025-joined_tdata.csv
Labels: documentation

#159 seagrass > algae
  classification/0-preprocessing-tdata-geopandas.ipynb
  classification/1-generate-postcard-csv.ipynb
  classification/4-prediction.ipynb
  classification/training-data/nm-bootless-bay-13072025_postcard.geojson
  classification/training-data/nm-serua-14072025_postcard.geojson
  classification/utils.py
Labels: documentation, enhancement

#160 updated function for preprocessing automated
  classification/0-preprocessing-tdata-geopandas.ipynb
  classification/1-generate-postcard-csv.ipynb
  classification/utils.py
Labels: documentation, enhancement

#161 Automation for notebook 1 > through all geojson postcards
  classification/1-generate-postcard-csv.ipynb
  classification/automated_notebook_runs/executed_notebooks/bootless-bay_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/korotogo_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/mana-north_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/mana-south_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/nm-bootless-bay-26072025_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/nm-korotogo-26072025_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/nm-mana-north-26072025_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/nm-mana-south-26072025_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/nm-paunganisu-26072025_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/nm-serua-26072025_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/nm-serua_2-26072025_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/nm-suva_central-26072025_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/nm-suva_east-26072025_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/nm-suva_west-26072025_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/nm-tulagi-26072025_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/nm-yanuca-26072025_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/paunganisu_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/serua_2_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/serua_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/suva_central_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/suva_east_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/suva_west_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/tulagi_postcard_executed.ipynb
  classification/automated_notebook_runs/executed_notebooks/yanuca_postcard_executed.ipynb
  classification/run_automation.py
Labels: documentation
